config/routes.rb
Mpcm::Engine.routes.draw do
  scope '/' do
    get '/articles/:id/edit_images', to: 'articles#edit_images', as: 'edit_images_article'
    resources :articles do
      resources :images, only: [:create, :destroy]
    end
  end
end

app/models/mpcm/application_record.rb
module Mpcm
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/mpcm/article.rb
module Mpcm
  class Article < ApplicationRecord
    validates :title, presence: true
    mount_uploaders :images, ImageUploader

    def formatted_creation_time
      unless !self.created_at
        self.created_at.strftime("%d/%m/%Y - %H:%M:%S")
      end
    end

    def formatted_update_time
      unless !self.updated_at
        self.updated_at.strftime("%d/%m/%Y - %H:%M:%S")
      end
    end

    def formatted_published_time
      unless !self.published_at
        self.published_at.strftime("%d/%m/%Y - %H:%M:%S")
      end
    end

    def formatted_published
      if self.published && self.published == true
        'Oui'
      else
        'Non'
      end
    end

    def formatted_height
      if self.height
        "#{self.height} cm"
      else
        'N/C'
      end
    end

    def formatted_width
      if self.width
        "#{self.width} cm"
      else
        'N/C'
      end
    end

    def formatted_depth
      if self.depth
        "#{self.depth} cm"
      else
        'N/C'
      end
    end

    def formatted_weigth
      if self.weigth
        "#{self.weigth} kg"
      else
        'N/C'
      end
    end

    def formatted_price
      if self.price
        "#{self.price} €"
      else
        'N/C'
      end
    end

    def to_param
      self.slug
    end
  end
end

app/controllers/mpcm/application_controller.rb
module Mpcm
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/mpcm/articles_controller.rb
require_dependency "mpcm/application_controller"
require 'fileutils'

module Mpcm
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :edit_images, :update, :destroy]
    after_action :set_slug, only: [:create, :update]
    after_action :set_published_date, only: [:create, :update]

    def index
      @articles = Article.all.order('updated_at DESC')
    end

    def show
      render :show
    end

    def new
      @article = Article.new

      render :new
    end

    def edit
      render :edit
    end

    def edit_images
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to article_path(@article), notice: 'Article créé avec succès'
      else
        render :new
      end
    end

    def update
      if @article.update(article_params)
        redirect_to article_path(@article), notice: 'Article sauvegardé avec succès'
      else
        render :edit
      end
    end

    def destroy
      saved_id = @article.id
      @article.destroy
      delete_images_folder(saved_id)
      redirect_to articles_path, notice: 'Article supprimé avec succès'
    end

    private

    def set_article
      @article = Article.find_by_slug(params[:id])
    end

    def article_params
      params.require(:article).permit(:id,
                                      :title,
                                      :content,
                                      :slug,
                                      :height,
                                      :width,
                                      :depth,
                                      :weigth,
                                      :price,
                                      {images: []},
                                      :published
                                      )
    end

    def set_slug
      if @article[:slug].blank?
        @article.update_attribute :slug, @article[:title].parameterize
      else
        @article.update_attribute :slug, @article[:slug].parameterize
      end
    end

    def set_published_date
      if @article.published
        @article.update_attribute :published_at, Time.zone.now
      else
        @article.update_attribute :published_at, nil
      end
    end

    def delete_images_folder id
      FileUtils.remove_dir "#{Rails.root}/public/uploads/mpcm/article/images/#{id}", true
    end
  end
end

app/controllers/mpcm/images_controller.rb
require_dependency "mpcm/application_controller"

module Mpcm
  class ImagesController < ApplicationController
  	before_action :set_article

  	def create
  		add_more_images(images_params[:images])
  		flash[:error] = 'Erreur, impossible d\'ajouter l\'image' unless @article.save
  		redirect_to :back
  	end

    def destroy
      remove_image_at_index(params[:id].to_i)
      flash[:error] = 'Impossible de supprimer l\'image' unless @article.save
      redirect_to :back
    end

  	private

  	def set_article
  		@article = Article.find(params[:article_id])
  	end

  	def add_more_images new_images
  		images = @article.images
  		images += new_images
  		@article.images = images
  	end

    def remove_image_at_index index
      remain_images = @article.images
      deleted_image = remain_images.delete_at(index)
      deleted_image.try(:remove!)
      @article.images = remain_images
      @article.remove_images! if remain_images.empty?
    end

  	def images_params
  		params.require(:article).permit({images: []})
  	end
  end
end

app/helpers/mpcm/application_helper.rb
module Mpcm
  module ApplicationHelper
  end
end

app/helpers/mpcm/articles_helper.rb
module Mpcm
  module ArticlesHelper
  end
end

app/helpers/mpcm/images_helper.rb
module Mpcm
  module ImagesHelper
    def carousel_for images
      Carousel.new(self, images).html
    end

    class Carousel
      def initialize view, images
        @view, @images = view, images
        @uid = SecureRandom.hex(6)
      end

      def html
        content = safe_join([indicators, slides, controls])
        content_tag(:div, content, id: uid, class: 'carousel slide')
      end

      private

      attr_accessor :view, :images, :uid
      delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

      def indicators
        items = images.count.times.map { |index| indicator_tag(index) }
        content_tag(:ol, safe_join(items), class: 'carousel-indicators')
      end

      def indicator_tag index
        options = {
          class: (index.zero? ? 'active' : ''),
          data: {
            target: uid,
            slide_to: index
          }
        }

        content_tag(:li, '', options)
      end

      def slides
        items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
        content_tag(:div, safe_join(items), class: 'carousel-inner')
      end

      def slide_tag image, is_active
        options = {
          class: (is_active ? 'item active' : 'item')
        }

        content_tag(:div, image_tag(image), options)
      end

      def controls
        safe_join([control_tag('left'), control_tag('right')])
      end

      def control_tag direction
        options = {
          class: "#{direction} carousel-control",
          data: { slide: direction == 'left' ? 'prev' : 'next' }
        }

        icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
        control = link_to(icon, "##{uid}", options)
      end
    end
  end
end

app/views/layouts/mpcm/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mpcm</title>
  <%= stylesheet_link_tag    "mpcm/application", media: "all" %>
  <%= javascript_include_tag "mpcm/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mpcm/articles/edit.html.slim
h1 Modifier l'article

= simple_form_for(@article) do |f|
  = f.input :title, label: 'Titre', error: 'Un titre est obligatoire'
  = f.input :content, label: 'Contenu', as: :text
  = f.input :height, label: 'Hauteur', hint: 'Facultatif', as: :float
  = f.input :width, label: 'Largeur', hint: 'Facultatif', as: :float
  = f.input :depth, label: 'Profondeur', hint: 'Facultatif', as: :float
  = f.input :weigth, label: 'Poids', hint: 'Facultatif', as: :float
  = f.input :price, label: 'Prix', hint: 'Facultatif', as: :float
  = f.input :published, label: 'Publié ?', hint: 'Cochez la case pour publié l\'article', as: :radio_buttons, collection: [['Oui', true], ['Non', false]]
  = f.input :slug, label: 'Nom de l\'URL', hint: 'Facultatif'

  = f.submit 'Enregistrer'

= link_to 'Retour', articles_path
span  |
=< link_to 'Modifier les images', edit_images_article_path(@article)

app/views/mpcm/articles/edit_images.html.slim
td
  - @article.images.each_with_index do |image, index|
    div
      = image_tag(image.url)
      = link_to 'Supprimer', article_image_path(@article, index), method: :delete, data: { confirm: 'Êtes-vous sûre de vouloir supprimer cette image ?'}

= form_for @article, url: article_images_path(@article), method: :post do |f|
  .field
    = f.file_field :images, multiple: true
  .actions
    = f.submit 'Ajouter des images'

= link_to 'Retour', article_path(@article)

app/views/mpcm/articles/index.html.slim
h1 Articles

= link_to 'Nouvel article', new_article_path, class: 'btn btn-primary space-2'

table.table.space-4
  thead
    tr
      th Titre
      th Date de création
      th Publié ?
      th colspan='3'
  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = article.formatted_creation_time
        td = article.formatted_published
        td = link_to 'Voir', article_path(article)
        td = link_to 'Modifier', edit_article_path(article)
        td = link_to 'Supprimer', article_path(article), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }

= link_to 'Nouvel article', new_article_path, class: 'btn btn-primary space-2'

app/views/mpcm/articles/new.html.slim
h1 Nouvel article

= simple_form_for(@article) do |f|
  = f.input :title, label: 'Titre', error: 'Un titre est obligatoire'
  = f.file_field :images, multiple: true
  = f.input :content, label: 'Contenu', as: :text
  = f.input :height, label: 'Hauteur', hint: 'Facultatif', as: :float
  = f.input :width, label: 'Largeur', hint: 'Facultatif', as: :float
  = f.input :depth, label: 'Profondeur', hint: 'Facultatif', as: :float
  = f.input :weigth, label: 'Poids', hint: 'Facultatif', as: :float
  = f.input :price, label: 'Prix', hint: 'Facultatif', as: :float
  = f.input :published, label: 'Publié ?', hint: 'Cochez la case pour publié l\'article', as: :radio_buttons, collection: [['Oui', true], ['Non', false]], checked: true
  = f.input :slug, label: 'Nom de l\'URL', hint: 'Facultatif'

  = f.submit 'Enregistrer'

= link_to 'Retour', articles_path

app/views/mpcm/articles/show.html.slim
h1 #{@article.title}

= carousel_for(@article.images_urls)

h4 Contenu
p #{@article.content}

h4 Description
span Hauteur:
=< @article.formatted_height
br
span Largeur:
=< @article.formatted_width
br
span Profondeur:
=< @article.formatted_depth
br
span Poids:
=< @article.formatted_weigth
br
span Prix:
=< @article.formatted_price
br
= link_to 'Retour', articles_path
span  |
=< link_to 'Modifier', edit_article_path(@article)
span  |
=< link_to 'Modifier les images', edit_images_article_path(@article)

javascript:
  $(function(){
    $('.carousel').carousel({
      interval: false
    })
    $('.item:first').addClass('active');
  });